### ISSUE TITLE
Question Regarding Compilation Issue

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/gem-light-dqm#23]
## Brief summary of issue

When trying to compile via:

```bash
source compile.sh
```

It complains that command `g++-4.9.3` is not found on `gem904qc8daq`.  Is there a particular reason version `4.9.3` is required?

The `settings.sh` file also seems to try to reference:

```bash
cd $GEM_DQM_ROOT_BASE
source bin/thisroot.sh
cd -
export LD_LIBRARY_PATH=/usr/local/gcc/4.9.3/lib64:$LD_LIBRARY_PATH
export PATH=$PATH:$BUILD_HOME/gem-light-dqm/dqm-root/bin/linux/x86_64_slc6:$BUILD_HOME/gem-light-dqm/gemtreewriter/bin/linux/x86_64_slc6
```

There is no such directory `/usr/local/gcc` on the machine.

The light dqm manual I have:
[GEM_Light_DQM_Reference_Guide.pdf](https://github.com/cms-gem-daq-project/gem-light-dqm/files/2227315/GEM_Light_DQM_Reference_Guide.pdf)
 
does not specify installation requirements or what `$GEM_DQM_ROOT_BASE` should be (I guess a system install of `ROOT` location...?).

Compilation seems to work by just using `g++` version 4.8.5 on the machine.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [X] Question

## Your Environment

* Version used: branch `release-v3`
* Shell used: `bash`

**Comment by mexanick** [comment]
was fixed
