### ISSUE TITLE
DQM doesn't build on cosmicstandtif

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/gem-light-dqm#9]
Due to the hardcoded dependence on gcc 4.9.3, the DQM code was not building on cosmicstandtif
I installed 4.9.3 and it failed due to some include errors
We need to ensure that the environment on each machine is set up identically, but I don't know what's missing at the moment

**Comment by mexanick** [comment]
This is the error:
In file included from /usr/include/errno.h:36:0,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/cerrno:41,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/ext/string_conversions.h:44,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/bits/basic_string.h:2849,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/string:52,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/bits/locale_classes.h:40,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/bits/ios_base.h:41,
                 from /usr/local/gcc/4.9.3/include/c++/4.9.3/iomanip:40,
                 from /home/mdalchen/cms-gem-daq-project/gem-light-dqm/dqm-root/../../gem-light-dqm/dqm-root/src/common/histogramLayeringExample.cxx:1:
/usr/include/bits/errno.h:25:26: fatal error: /usr/local/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include-fixed/linux/errno.h: Permission denied
 # include <linux/errno.h>

It relates to the way how gcc is installed. I can see two issues:
1. Permissions for  /usr/local/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include-fixed/linux:
   ls -altrh /usr/local/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include-fixed/
   drwxr-x---. 2 root root 4.0K Sep  6 13:49 linux
2. The file errno.h under the folder above is actually missed. 

So I don't think we should consider this as a bug. I think first we need to fix the permissions (at 904 it looks like drwxr-xr-x. 2 root root 4.0K Jun 13 09:23 linux
Jared, could you please fix this as system administrator for that machine?

**Comment by jsturdy** [comment]
Yeah, that was it...
However, the file itself is not there (nor on gem904daq01), which was why I was a bit confused.
However, when changing the permissions, it now works fine...

**Comment by mexanick** [comment]
I think it now looks for it in a next include location. And before the crash was not like "I can't find file" but "I can't look at the place one told me to look"
